language: ruby

rvm:
  - 2.2
  - jruby
  - 2.6.3

services:
  - postgresql

before_install:
  - gem install bundler

script:
  - bundle exec rspec

after_script:
  - bundle exec rake coveralls:push

before_script:
  - psql -c 'CREATE DATABASE mla_rails_test;' -U postgres
  - bundle exec rake db:create db:schema:load